version: 2
jobs:
  build:
    docker:
      - image: microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet publish -o publish
  test:
    docker:
      - image: microsoft/aspnetcore-build:2.0
    steps:
      - checkout
      - run: echo "No tests"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test